=== georgespalding/JAXBSchemas-pub/cv/src/main/resources/META-INF/schema/omegapoint/omegapoint-cv.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema
        version="0.1"
        targetNamespace="http://www.omegapoint.se/2014/10/cv"
        xmlns="http://www.omegapoint.se/2014/10/cv"
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:xhtml="http://www.w3.org/1999/xhtml"
        elementFormDefault="qualified">
    <xs:import namespace="http://www.w3.org/1999/xhtml"
               schemaLocation="http://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd" />

    <xs:element name="CorriculumVitae" type="CV"/>

    <xs:simpleType name="Title">
        <xs:restriction base="xs:string">
            <xs:maxLength value="30" />
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="Keyword">
        <xs:restriction base="xs:string">
            <xs:maxLength value="12" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="XhtmlParagraph" mixed="true">
        <xs:complexContent>
            <xs:extension base="xhtml:Inline"/>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="CV">
        <xs:sequence>
            <xs:element name="Name" type="xs:string">
                <xs:annotation>
                    <xs:documentation xml:lang="sv">
                        Konsultens namn
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
            <xs:element name="Header" type="HeaderType"/>
            <xs:element name="PreviousExperience" type="ProjectExperienceType" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="Id" type="xs:ID" use="optional"/>
        <xs:attribute name="Version" type="xs:string" use="optional"/>
    </xs:complexType>
    <xs:complexType name="HeaderType">
        <xs:annotation>
            <xs:documentation xml:lang="sv">
                Snabbinfo som man skall kunna kan läsa på förstasidan.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="Pitch" type="PitchType"/>
            <xs:element name="ConsultantBlurb" type="ConsultantBlurbType"/>
            <xs:element name="PersonalBlurb" type="PersonalBlurpType"/>
            <xs:element name="BriefSkills" type="BriefSkillList"/>
            <xs:element name="SuitableRoles" type="SuitableRoleList"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PitchType">
        <xs:complexContent>
            <xs:extension base="XhtmlParagraph"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="ConsultantBlurbType" mixed="true">
        <xs:complexContent>
            <xs:extension base="xhtml:Inline"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="PersonalBlurpType">
        <xs:complexContent>
            <xs:extension base="XhtmlParagraph"/>
        </xs:complexContent>
    </xs:complexType>
    <xs:complexType name="BriefSkillList">
        <xs:sequence>
            <xs:element name="Title" type="Title" />
            <xs:sequence maxOccurs="7">
                <xs:element name="Area" type="Title" />
                <xs:element name="Skill" type="Keyword" maxOccurs="5" />
            </xs:sequence>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="SuitableRoleList">
        <xs:sequence>
            <xs:element name="Title" type="Title" />
            <xs:element name="Skill" type="Keyword" maxOccurs="5" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="ProjectExperienceType">
        <xs:sequence>
            <xs:element name="TODO"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== georgespalding/JAXBSchemas-pub/cv/src/main/resources/META-INF/schema/omegapoint/omegapoint-cv.xml
<cv:CorriculumVitae
        xmlns:cv="http://www.omegapoint.se/2014/10/cv"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.w3.org/1999/xhtml"
        xsi:schemaLocation="
            http://www.w3.org/1999/xhtml http://www.w3.org/2002/08/xhtml/xhtml1-strict.xsd
            http://www.omegapoint.se/2014/10/cv omegapoint-cv.xsd">
    <cv:Name>Werner Herzog</cv:Name>
    <cv:Header>
        <cv:BriefSkills>
            <cv:Title>Summering kompetens</cv:Title>
            <cv:Area>Konstarter</cv:Area>
            <cv:Skill>Keramik</cv:Skill>
            <cv:Skill>Skulptur</cv:Skill>
            <cv:Skill>Breakbeat</cv:Skill>
            <cv:Area>Programmering</cv:Area>
            <cv:Skill>Brainfuck</cv:Skill>
            <cv:Skill>f#</cv:Skill>
            <cv:Skill>Haskell</cv:Skill>
        </cv:BriefSkills>
    </cv:Header>
</cv:CorriculumVitae>
